### PR TITLE
Update to reflect latest 0.9 changes

### PR DESCRIPTION
**Pull request by thecodeassassin**
changed name to measurement to reflect latest stable version

### CODE REVIEW

**Comment by codeslash** [comment]
It was too confusing before I found this PR. thanks @thecodeassassin 
+1

**Comment by danibrutal** [comment]
+1!

**Comment by mjmeijerman** [comment]
+1

**Comment by beckettsean** [comment]
@thecodeassassin Thanks for the PR, but this repo is no longer active. The current documentation has moved to influxdb/influxdb.com. The page you reference in that repo has already been updated to the new line protocol: https://github.com/influxdb/influxdb.com/blob/master/content/docs/v0.9/concepts/reading_and_writing_data.md.

**Pull request closed without merging**
