### PR TITLE
first pass at fixing aggregate_functions

### PR DESCRIPTION
**Pull request by beckettsean**

### CODE REVIEW

**Comment by beckettsean** [comment]
addresses #125

**Comment by pauldix** [comment]
Looks good. The only other thing I'd add is something at the top about using `GROUP BY` with tag keys to produce multiple series that have the aggregate applied. So you can group by time and tags.

**Comment by gunnaraasen** [comment]
+1 May want to separate the `GROUP BY` stuff into it's own section at the top of the page.

**Comment by beckettsean** [comment]
I'll merge this and come back for a pass at the GROUP BY behavior.

**Pull request merged**
