### PR TITLE
InfluxQL: advise to specify time range when using GROUP BY

### PR DESCRIPTION
**Pull request by nemesisdesign**
Referencing https://github.com/influxdb/influxdb/issues/1904;

### CODE REVIEW

**Comment by nemesisdesign** [comment]
@otoolep @toddboom any thoughts on this?

**Comment by otoolep** [comment]
This looks fine, I'll merge it. @toddboom -- revert if necessary.

**Comment by otoolep** [comment]
Thanks @nemesisdesign

**Comment by nemesisdesign** [comment]
welcome, glad to help out

**Pull request merged**
